workflows:
  ios-simulator-build:
    name: iOS Simulator Build (iOS 13+)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set minimum iOS version to 13.0
        script: |
          sed -i '' 's/PLATFORM_VERSION = .*/PLATFORM_VERSION = 13.0;/' ios/Flutter/Generated.xcconfig || true
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build for iOS Simulator
        script: flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app

  android-release-build:
    name: Android Release Build
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
