// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCciT8JtSqdzyEitXabVBFszP0oZ7aZEtc',
    appId: '1:289296400251:web:ff187f542352e06cccc7de',
    messagingSenderId: '289296400251',
    projectId: 'blokade-87f3d',
    authDomain: 'blokade-87f3d.firebaseapp.com',
    storageBucket: 'blokade-87f3d.firebasestorage.app',
    measurementId: 'G-7K7B4NXMLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOSGnQPSKo0SdooDjCZ1RUstZA9D7tOek',
    appId: '1:289296400251:android:dc46506c5b674ca9ccc7de',
    messagingSenderId: '289296400251',
    projectId: 'blokade-87f3d',
    storageBucket: 'blokade-87f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjfPR1QdQFyyfltHtcEW02sDX0ARmbt4',
    appId: '1:289296400251:ios:b6e65a8f6c400c60ccc7de',
    messagingSenderId: '289296400251',
    projectId: 'blokade-87f3d',
    storageBucket: 'blokade-87f3d.firebasestorage.app',
    iosBundleId: 'com.example.blokade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjfPR1QdQFyyfltHtcEW02sDX0ARmbt4',
    appId: '1:289296400251:ios:b6e65a8f6c400c60ccc7de',
    messagingSenderId: '289296400251',
    projectId: 'blokade-87f3d',
    storageBucket: 'blokade-87f3d.firebasestorage.app',
    iosBundleId: 'com.example.blokade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCciT8JtSqdzyEitXabVBFszP0oZ7aZEtc',
    appId: '1:289296400251:web:863f04787e108429ccc7de',
    messagingSenderId: '289296400251',
    projectId: 'blokade-87f3d',
    authDomain: 'blokade-87f3d.firebaseapp.com',
    storageBucket: 'blokade-87f3d.firebasestorage.app',
    measurementId: 'G-YMWN6Z151Y',
  );
}
