   platform :ios, '13.0'

   # CocoaPods master repo
   source 'https://github.com/CocoaPods/Specs.git'

   # Pods for your app
   target 'Runner' do
     # Pod for Firebase and other dependencies
     pod 'Firebase/Core'
     pod 'cloud_firestore','~> 5.6.6'
     pod 'firebase_storage','~> 12.4.5'
   end
