   platform :ios, '13.0'

   # CocoaPods master repo
   source 'https://github.com/CocoaPods/Specs.git'

   # Pods for your app
   target 'Runner' do
       use_frameworks!
     # Pod for Firebase and other dependencies
     pod 'Firebase/Core','~>3.13.0'
     pod 'Firebase/Firestore','~> 5.6.6'
     pod 'Firebase/Storage','~> 12.4.5'


   end

